apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-a-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: counter-a
  template:
    metadata:
      labels:
        app: counter-a
    spec:
      containers:
        - name: counter-a
          image: yash5090/counter-a:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
